### PR TITLE
Cnnetantwo 25

### PR DESCRIPTION
**Pull request by dsover**
implement thumbnail image module on content details page

FIXES: CNNETANTWO-25 http://tickets.turner.com/browse/CNNETANTWO-25
**see https://github.com/cnnlabs/cnn-antools-factors-fe/pull/28 for testing information

screen shot 2017-08-10 at 3 26 05 pm

screen shot 2017-08-10 at 3 26 27 pm

### CODE REVIEW

**Comment by dsover** [comment]
@jamsyoung this passes test on my local see screen shot
screen shot 2017-08-10 at 3 42 05 pm

**Comment by khowen** [comment]
Mine are passing too locally on this branch.

screen shot 2017-08-10 at 3 43 24 pm

**Comment by jamsyoung** [comment]
How are you starting up the app to run the tests? @khowen @dsover 

I am doing: 

```bash
$ nvm install                # which did go to the new 8.3.0
$ . .ignore/env.sh           # which contains the 2 dynaimage env vars
$ npm i -g jq-cli-wrapper    # required since a new node version was installed
$ npm test
```

**Comment by jamsyoung** [comment]
Ok.
This works on node 8.2.1

This fails in node 8.3.0

Since node 8.3.0 is released, and we use the most current version, we need to figure out what changed.

**Comment by dsover** [comment]
I think it is the package-lock.json I think when the node version updates some dependancies are breaking down stream. try removing that file and testing again

**Comment by jamsyoung** [comment]
Yep, it was def the package-lock.file.

now we know. ;)

**Pull request merged**
